# Generated by Django 5.1.2 on 2024-10-31 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_watch_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch_review',
            old_name='products',
            new_name='product',
        ),
    ]
